version: '3'
networks: 
    app:
        driver: bridge

services: 
    webserver:
        depends_on: 
            - php
            - db
        image: nginx:stable-alpine 
        container_name: webserver
        ports: 
            - "8000:80"
        volumes: 
            - ./server:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - app
        depends_on: 
            - db
            - php
    db:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports: 
            - "4306:3306"
        volumes: 
            - ./db:/var/lib/db
        environment:      
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
            MYSQL_DATABASE: 'news'
            MYSQL_ROOT_PASSWORD: 'root'
        networks: 
            - app
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./server:/var/www/html
        ports: 
            - "9000:9000"
        networks: 
            - app