version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    api:    
        build: .
        container_name: laravel_backend
        networks: 
            - laravel
        volumes: 
            - ./server:/var/www
        ports: 
            - "8000:8000"
        depends_on: 
            - db            
    db:       
        image: mysql:latest 
        container_name: database
        volumes: 
            - .dbdata:/var/lib/mysql
        environment:      
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
            MYSQL_DATABASE: 'news'
            MYSQL_ROOT_PASSWORD: 'root'

        networks: 
            - laravel