version: '3'

networks: 
    app:
        driver: bridge

services: 
    api:    
        build: ./server
        container_name: backend
        networks: 
                - app
        volumes: 
            - ./server:/app/api   
        ports: 
            - "8001:8000"
        depends_on: 
            - db
            
    db:       
        image: mysql:latest 
        container_name: database
        volumes: 
            - .dbdata:/var/lib/mysql
        environment:      
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
            MYSQL_DATABASE: 'news'
            MYSQL_ROOT_PASSWORD: 'root'

        networks: 
            - app
