export const FETCH_FAVORITE_REQUEST = 'FETCH_FAVORITE_REQUEST'
export const FETCH_FAVORITE_SUCCESS = 'FETCH_FAVORITE_SUCCESS'
export const FETCH_FAVORITE_FAILURE = 'FETCH_FAVORITE_FAILURE'
export const DELETE_FROM_FAVORITE   = 'DELETE_FROM_FAVORITE'